on:
  push:
    branches:
    - main
    paths:
    - 'src/**'

jobs:
  aws-lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r -o src.zip src/*
      - uses: actions/upload-artifact@v4.3.1
        with:
          path: .
          name: src.zip
          if-no-files-found: error
          overwrite: true
      - name: Deploy AWS Lambda
        uses: embeddedinn/deploy_lambda@v1.0.0
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          lambda-name: ${{ secrets.LAMBDA_NAME }}
          zip-file: src.zip
